# This Cloud Build file has a multi-stage deployment process.
# 1. Build and push the Docker image.
# 2. Deploy to a "development" Cloud Run service (`portfolio-app`).
# 3. Deploy to the "production" Cloud Run service (`portfolio-app-prod`).

steps:
  # 1. Install dependencies
  - name: 'node:18'
    id: 'Install-Dependencies'
    entrypoint: npm
    dir: 'apps-portfolio'
    args: ['install']

  # 2. Import data
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Import-Data-To-SQLite'
    entrypoint: npx
    dir: 'apps-portfolio'
    args: ['tsx', 'scripts/import-yaml.ts']
    env:
      - 'DATABASE_URL=file:./db/portfolio.sqlite3'
    waitFor: ['Install-Dependencies']

  # 3. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    dir: 'apps-portfolio'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'
      - '--build-arg'
      - 'DATABASE_URL=file:/app/db/portfolio.sqlite3'
      - '.'
    waitFor: ['Import-Data-To-SQLite']

  # 4. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push-Image'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'
    waitFor: ['Build']

  # 5. Deploy to Development (Cloud Run)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy-Dev'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - "$_APP_NAME_DEV" # 'portfolio-app'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--set-env-vars=RICC_ENV=$_RICC_ENV'
    env:
      - '_RICC_ENV=$_RICC_ENV'
    waitFor: ['Push-Image']

  # 6. Deploy to Production (Cloud Run)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy-Prod'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - "$_APP_NAME_PROD" # 'portfolio-app-prod'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--set-env-vars=RICC_ENV=CloudBuild.yaml'
    waitFor: ['Deploy-Dev']

# Store the image in Artifact Registry
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'

# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
# COMMON ENV VARS
substitutions:
    _CLOUD_RUN_REGION: 'europe-west1'
    _APP_NAME_DEV: 'portfolio-app'
    _APP_NAME_PROD: 'portfolio-app-prod'
    _RICC_ENV: 'CloudBuild.yaml'

steps:
  # 0. Get the version
  - name: 'ubuntu'
    id: Version
    entrypoint: 'bash'
    dir: 'apps-portfolio'
    args:
      - '-c'
      - 'cat VERSION > /workspace/VERSION'

    substitutionOption: 'ALLOW_LOOSE'

# Set a timeout for the build
timeout: '1200s'
