# This Cloud Build file has a multi-stage deployment process.
# 1. Build and push the Docker image.
# 2. Deploy to a "development" Cloud Run service (`portfolio-app`).
# 3. Deploy to the "production" Cloud Run service (`portfolio-app-prod`).

steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    dir: 'apps-portfolio'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'
      - '--build-arg'
      - 'DATABASE_URL=file:/app/db/portfolio.sqlite3'
      - '.'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'
    waitFor: ['Build']

  # 3. Deploy to development
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy-Dev
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - "$_APP_NAME_DEV" # 'portfolio-app'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--set-env-vars=RICC_ENV=$_RICC_ENV'
    env:
      - '_RICC_ENV=$_RICC_ENV'
    waitFor: ['Push']

  # 4. Deploy to production
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy-Prod
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - "$_APP_NAME_PROD" # 'portfolio-app-prod'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--set-env-vars=RICC_ENV=CloudBuild.yaml'
    waitFor: ['Deploy-Dev']

# Store the image in Artifact Registry
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/portfolio-app:latest'

# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
# COMMON ENV VARS
substitutions:
    _CLOUD_RUN_REGION: 'europe-west1'
    _APP_NAME_DEV: 'portfolio-app'
    _APP_NAME_PROD: 'portfolio-app-prod'
    _RICC_ENV: 'CloudBuild.yaml'

options:
    substitutionOption: 'ALLOW_LOOSE'

# Set a timeout for the build
timeout: '1200s'
