# List
list:
    just -l


# Initialize the project (create venv and install deps)
init:
    uv venv
    uv pip install -e .[dev]

# Install dependencies and the project in editable mode
install:
    uv pip install -e .[dev]

# Run the geniectl script for max 30 seconds
run:
    #!/bin/bash
    export PATH=~/go/bin/:$PATH
    export GENIECTL_EVAL=false
    bash -c "uv run geniectl apply -f etc/story-generation.yaml"

run-on-another-dir-and-eval:
    #!/bin/bash
    export PATH=~/go/bin/:$PATH
    export GENIECTL_EVAL=true
    bash -c "uv run geniectl apply -f etc/story-generation.yaml  --output-dir out2/"

plan:
    uv run geniectl apply -f etc/story-generation.yaml --plan

eval:
    #!/bin/bash
    export PATH=~/go/bin/:$PATH
    bash -c "uv run geniectl eval -f etc/story-generation.yaml"
eval2:
    #!/bin/bash
    export PATH=~/go/bin/:$PATH
    bash -c "uv run geniectl eval -f etc/story-generation.yaml --output-dir out2/"

# --- Publishing ---

# Build the package for distribution
build:
    uv run python -m build

# Publish the package to TestPyPI (requires a TestPyPI account)
publish-test:
    twine upload --repository testpypi dist/*

# Publish the package to PyPI (requires a PyPI account)
publish: build
    #echo 'Make sure you just build before publishing!'
    uv run twine upload dist/*

# --- Testing ---

test:
    uv run pytest


run-test:
    uv run geniectl apply -f etc/story-generation.yaml --verbose

auth:
    #!/bin/bash

    set -euo pipefail
    . .env
    echo "Setting up environment variables for authentication..."
    echo "- GOOGLE_CLOUD_PROJECT: $GOOGLE_CLOUD_PROJECT"
    echo "- GOOGLE_CLOUD_LOCATION: ${GOOGLE_CLOUD_LOCATION}"
    gcloud config set project $GOOGLE_CLOUD_PROJECT
    gcloud config set compute/region $GOOGLE_CLOUD_LOCATION
    gcloud auth application-default login
    gcloud auth application-default print-access-token

# --- GCP Setup ---
# gcp-create-service-account:
#     bin/gcp-setup.sh create-service-account

# gcp-grant-iam-to-service-account:
#     bin/gcp-setup.sh grant-iam-to-service-account

# gcp-create-service-account-key:
#     bin/gcp-setup.sh create-service-account-key

# gcp-revoke-iam:
#     bin/gcp-setup.sh revoke-iam

# gcp-grant-iam:
#     bin/gcp-setup.sh grant-iam

plan2:
    uv run geniectl apply -f etc/02-video-idea.yaml --plan --verbose -d out/rubycon/

gemini:
    gemini -c --approval-mode auto_edit

test-json:
    @echo This only works with gemini-cli v0.6.0 or later
    gemini -v
    gemini  --output-format json --yolo -p 'show me the PATH env, and tell me if ~/go/bin is in the PATH' # | jq .

