
# List
list:
    just -l


# Install dependencies and the project in editable mode
install:
    uv pip install -e .[dev]

# Run the geniectl script
run:
    uv run geniectl apply -f /Users/ricc/git/vibecoding/geniectl/etc/story-generation.yaml

# --- Publishing ---

# Build the package for distribution
build:
    python -m build

# Publish the package to TestPyPI (requires a TestPyPI account)
publish-test:
    twine upload --repository testpypi dist/*

# Publish the package to PyPI (requires a PyPI account)
publish:
    twine upload dist/*

# --- Testing ---

test:
    pytest


# run-test:
#     uv run python src/geniectl/cli.py apply -f etc/story-generation.yaml --verbose
